name: AutoData-Collection

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'

jobs:
  get-json:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install requests
      run: |
       pip install requests
       pip install selenium requests futures eventlet

    - name: Run Python
      run: |
       python v2ray.py
       python iptv.py
       python main.py

    - name: Push
      run: |
        git config --local user.email "cymz6@hotmail.com"
        git config --local user.name "acymz"
        git add .
        git commit -m 'Auto-Update'
        git push -f
